[package]
name = "axum-example"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
axum = "0.7"
lasso = { version = "0.7" }
measured = { path = "../../core", features = ["lasso"] }
tokio = { version = "1", features = ["full"] }
