[package]
name = "measured"
version = "0.0.6"
edition = "2021"
description = "A better way to measure your application performance"
authors = ["Conrad Ludgate <conradludgate@gmail.com"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/conradludgate/measured"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: add features for the dependencies
indexmap = "2"
lasso = { version = "0.7", features = ["multi-threaded"] }
bytes = "1"
memchr = "2"
ryu = "1"
itoa = "1"
rustc-hash = "1"
hashbrown = "0.14"
parking_lot = "0.12"
dashmap = "5"

measured-derive = { path = "../derive", version = "0.0.6" }

[dev-dependencies]
fake = "2.9.2"
divan = "0.1.11"
prometheus = { version = "0.13", default-features = false }
metrics = "0.22"
metrics-exporter-prometheus = { version = "0.13", default-features = false }
rand = "0.8"

[[bench]]
name = "counters"
harness = false
