[package]
name = "measured-prometheus-protobuf"
version = "0.0.21"
edition = "2021"
description = "Tokio metrics for measured"
authors = ["Conrad Ludgate <conradludgate@gmail.com"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/conradludgate/measured"
readme = "README.md"

[dependencies]
measured = { path = "../core", version = "0.0.21" }
prost = "0.12"
prost-types = "0.12"
bytes = "1"
ryu = "1"
itoa = "1"
